"""
Mock data representing third-party data products across:
- SaaS APIs (REST/GraphQL)
- Database access (Snowflake, Redshift, Postgres)
- Datalake (S3/Delta Lake)
- SNS Topics / Event streams

Procurement metadata is mocked as if extracted from PDF contracts.
In production, wire this to a PDF parser (pdfplumber + Claude extraction).
"""

DATA_CATALOG = {
    "products": [
        {
            "id": "credit_pulse_pro",
            "name": "CreditPulse Pro",
            "vendor": "Experian Data Services",
            "domain": "Financial / Credit Risk",
            "access_type": "database",
            "description": "Comprehensive consumer credit profiles with bureau scores, tradeline history, and derogatory records. Delivered via dedicated Snowflake share.",
            "tags": ["credit", "financial", "risk", "consumer", "bureau", "snowflake"],
            "data_freshness": "Daily (T+1)",
            "record_count": "250M+ US consumer records",
            "coverage": "United States",
            "owner_team": "Risk Analytics",
            "contact": "risk-data@company.internal",
            "status": "active",
            "onboarded_date": "2022-03-15",
            "vendor_tier": "Strategic",
        },
        {
            "id": "weather_core_api",
            "name": "WeatherCore API",
            "vendor": "AccuWeather Enterprise",
            "domain": "Environmental / Weather",
            "access_type": "saas_api",
            "description": "Real-time and historical weather data via REST API. Supports point, grid, and polygon queries. Hourly, daily, and 15-min intervals.",
            "tags": ["weather", "climate", "real-time", "api", "environmental", "forecast"],
            "data_freshness": "Real-time (15-min updates)",
            "record_count": "Global coverage, 2M+ stations",
            "coverage": "Global",
            "owner_team": "Data Platform",
            "contact": "data-platform@company.internal",
            "status": "active",
            "onboarded_date": "2021-07-01",
            "vendor_tier": "Standard",
        },
        {
            "id": "brand_sense_360",
            "name": "BrandSense 360",
            "vendor": "Brandwatch Ltd",
            "domain": "Marketing / Social Intelligence",
            "access_type": "saas_api",
            "description": "Social media listening and brand intelligence. Mentions, sentiment, reach, and influencer data across Twitter/X, Instagram, Reddit, news. REST API + webhook delivery.",
            "tags": ["social", "brand", "sentiment", "marketing", "twitter", "reddit", "api"],
            "data_freshness": "Near real-time (2-5 min lag)",
            "record_count": "1.4T+ historical mentions",
            "coverage": "Global, 100M+ sources",
            "owner_team": "Brand & Marketing Analytics",
            "contact": "marketing-data@company.internal",
            "status": "active",
            "onboarded_date": "2023-01-10",
            "vendor_tier": "Standard",
        },
        {
            "id": "geo_matrix_demographics",
            "name": "GeoMatrix Demographics",
            "vendor": "ESRI DataPlus",
            "domain": "Geospatial / Demographics",
            "access_type": "datalake",
            "description": "Census-enriched demographic and socioeconomic data at zip, tract, block-group level. Delivered as Delta Lake tables on S3. Annual refresh with quarterly patches.",
            "tags": ["demographics", "geospatial", "census", "zip", "income", "population", "datalake", "delta"],
            "data_freshness": "Annual (quarterly patches)",
            "record_count": "33K+ zip codes, 74K+ census tracts",
            "coverage": "United States",
            "owner_team": "Customer Analytics",
            "contact": "customer-analytics@company.internal",
            "status": "active",
            "onboarded_date": "2021-11-20",
            "vendor_tier": "Standard",
        },
        {
            "id": "market_pulse_events",
            "name": "MarketPulse Events",
            "vendor": "Refinitiv (LSEG)",
            "domain": "Financial Markets / Real-time",
            "access_type": "sns_topic",
            "description": "Real-time market events (trades, quotes, corporate actions, news) delivered via AWS SNS topic subscription. Covers equities, FX, commodities, fixed income.",
            "tags": ["market-data", "real-time", "equities", "fx", "sns", "streaming", "financial"],
            "data_freshness": "Real-time (<50ms latency)",
            "record_count": "~12M events/day",
            "coverage": "Global exchanges (150+)",
            "owner_team": "Quantitative Research",
            "contact": "quant-research@company.internal",
            "status": "active",
            "onboarded_date": "2023-06-01",
            "vendor_tier": "Strategic",
        },
        {
            "id": "transact_iq",
            "name": "TransactIQ Consumer",
            "vendor": "Mastercard Data & Services",
            "domain": "Consumer Transactions",
            "access_type": "datalake",
            "description": "Aggregated, anonymised consumer spend data by merchant category, geography, and demographic band. No individual-level PII. Delivered as Parquet files on S3, weekly refresh.",
            "tags": ["transactions", "spend", "consumer", "anonymised", "parquet", "datalake", "mastercard"],
            "data_freshness": "Weekly (T+7)",
            "record_count": "Aggregated; 45B+ underlying transactions/year",
            "coverage": "United States, UK, EU",
            "owner_team": "Consumer Insights",
            "contact": "consumer-insights@company.internal",
            "status": "active",
            "onboarded_date": "2022-09-05",
            "vendor_tier": "Strategic",
        },
        {
            "id": "health_insights_pro",
            "name": "HealthInsights Pro",
            "vendor": "IQVIA Holdings",
            "domain": "Healthcare / Claims",
            "access_type": "database",
            "description": "De-identified US healthcare claims data (medical + Rx). Procedure codes, diagnosis codes, provider specialty, payer mix. Delivered via dedicated Redshift schema.",
            "tags": ["healthcare", "claims", "medical", "rx", "hipaa", "de-identified", "redshift"],
            "data_freshness": "Monthly (30-45 day claims lag)",
            "record_count": "300M+ de-identified patient journeys",
            "coverage": "United States",
            "owner_team": "Health Economics",
            "contact": "health-data@company.internal",
            "status": "active",
            "onboarded_date": "2023-03-01",
            "vendor_tier": "Strategic",
        },
        {
            "id": "supply_shield_risk",
            "name": "SupplyShield Risk",
            "vendor": "Dun & Bradstreet",
            "domain": "Supply Chain / Risk",
            "access_type": "saas_api",
            "description": "Supplier risk intelligence: financial stability scores, ESG ratings, sanction screening, news risk alerts. REST API with optional SNS risk-alert subscription.",
            "tags": ["supply-chain", "risk", "sanctions", "esg", "supplier", "api", "alerts"],
            "data_freshness": "Daily scores; real-time alerts",
            "record_count": "500M+ global business entities",
            "coverage": "Global (190+ countries)",
            "owner_team": "Procurement & Risk",
            "contact": "supply-risk@company.internal",
            "status": "active",
            "onboarded_date": "2024-01-15",
            "vendor_tier": "Standard",
        },
    ]
}

SCHEMAS = {
    "credit_pulse_pro": {
        "access_type": "database",
        "connection": {
            "type": "snowflake",
            "account": "experian-share.snowflakecomputing.com",
            "database": "EXPERIAN_CREDIT_SHARE",
            "schema": "CONSUMER_CREDIT",
            "auth_method": "OAuth2 (SSO via Okta)",
            "warehouse": "ANALYTICS_WH",
            "role": "CREDIT_DATA_READER",
            "note": "Access via Snowflake Data Sharing - no data movement. Request access through IT portal."
        },
        "tables": [
            {
                "name": "CONSUMER_CREDIT_PROFILE",
                "description": "Core credit bureau attributes per consumer (hashed identity)",
                "row_count_approx": "250M",
                "columns": [
                    {"name": "CONSUMER_HASH_ID", "type": "VARCHAR(64)", "nullable": False, "pii": True, "description": "SHA-256 hash of PII key — never expose raw"},
                    {"name": "CREDIT_SCORE", "type": "INTEGER", "nullable": False, "pii": False, "description": "VantageScore 4.0 (300-850)"},
                    {"name": "SCORE_MODEL", "type": "VARCHAR(32)", "nullable": False, "pii": False, "description": "Scoring model used"},
                    {"name": "SCORE_DATE", "type": "DATE", "nullable": False, "pii": False, "description": "Date score was generated"},
                    {"name": "DEROGATORY_COUNT", "type": "INTEGER", "nullable": True, "pii": False, "description": "Number of derogatory marks"},
                    {"name": "PAYMENT_HISTORY_SCORE", "type": "FLOAT", "nullable": True, "pii": False, "description": "0-100 normalized payment history"},
                    {"name": "DEBT_TO_INCOME_BAND", "type": "VARCHAR(16)", "nullable": True, "pii": False, "description": "Banded DTI: LOW/MEDIUM/HIGH/VERY_HIGH"},
                    {"name": "CREDIT_UTILIZATION_PCT", "type": "FLOAT", "nullable": True, "pii": False, "description": "Revolving utilization 0-100"},
                    {"name": "AGE_OF_OLDEST_ACCOUNT_MONTHS", "type": "INTEGER", "nullable": True, "pii": False, "description": "Credit history depth in months"},
                    {"name": "STATE_CODE", "type": "CHAR(2)", "nullable": True, "pii": False, "description": "US state (2-letter)"},
                    {"name": "RECORD_DATE", "type": "DATE", "nullable": False, "pii": False, "description": "Partition key — daily"},
                ],
            },
            {
                "name": "TRADELINE_SUMMARY",
                "description": "Aggregated tradeline counts by account type",
                "row_count_approx": "250M",
                "columns": [
                    {"name": "CONSUMER_HASH_ID", "type": "VARCHAR(64)", "nullable": False, "pii": True, "description": "FK to CONSUMER_CREDIT_PROFILE"},
                    {"name": "ACCOUNT_TYPE", "type": "VARCHAR(32)", "nullable": False, "pii": False, "description": "MORTGAGE/AUTO/CREDIT_CARD/STUDENT/PERSONAL"},
                    {"name": "OPEN_COUNT", "type": "INTEGER", "nullable": True, "pii": False, "description": "Open accounts of this type"},
                    {"name": "CLOSED_COUNT", "type": "INTEGER", "nullable": True, "pii": False, "description": "Closed accounts"},
                    {"name": "DELINQUENT_COUNT", "type": "INTEGER", "nullable": True, "pii": False, "description": "30+ days past due"},
                    {"name": "TOTAL_BALANCE_BAND", "type": "VARCHAR(16)", "nullable": True, "pii": False, "description": "Banded: <10K / 10K-50K / 50K-100K / >100K"},
                    {"name": "RECORD_DATE", "type": "DATE", "nullable": False, "pii": False, "description": "Partition key"},
                ],
            },
        ],
        "sample_queries": {
            "data_scientist": "SELECT CREDIT_SCORE, DEBT_TO_INCOME_BAND, CREDIT_UTILIZATION_PCT, DEROGATORY_COUNT FROM CONSUMER_CREDIT.CONSUMER_CREDIT_PROFILE WHERE RECORD_DATE = CURRENT_DATE - 1 AND STATE_CODE = 'CA' LIMIT 1000;",
            "data_engineer": "SELECT RECORD_DATE, COUNT(*) as record_count FROM CONSUMER_CREDIT.CONSUMER_CREDIT_PROFILE GROUP BY RECORD_DATE ORDER BY RECORD_DATE DESC LIMIT 30;",
        },
    },
    "weather_core_api": {
        "access_type": "saas_api",
        "base_url": "https://api.accuweather-enterprise.com/v3",
        "auth_method": "API Key (header: X-API-Key)",
        "rate_limits": {"requests_per_minute": 1000, "requests_per_month": 10000000},
        "endpoints": [
            {
                "path": "/current-conditions/{locationKey}",
                "method": "GET",
                "description": "Current weather for a location",
                "params": [
                    {"name": "locationKey", "in": "path", "type": "string", "required": True, "description": "AccuWeather location ID"},
                    {"name": "details", "in": "query", "type": "boolean", "required": False, "description": "Include extended fields"},
                    {"name": "units", "in": "query", "type": "string", "enum": ["metric", "imperial"], "required": False},
                ],
                "response_fields": [
                    {"name": "EpochTime", "type": "integer", "description": "Unix timestamp"},
                    {"name": "Temperature.Value", "type": "number", "description": "Temperature in requested units"},
                    {"name": "Temperature.Unit", "type": "string"},
                    {"name": "WeatherIcon", "type": "integer", "description": "1-44 icon code"},
                    {"name": "WeatherText", "type": "string", "description": "Human-readable condition"},
                    {"name": "PrecipitationSummary.Precipitation.Value", "type": "number"},
                    {"name": "Wind.Speed.Value", "type": "number"},
                    {"name": "Wind.Direction.Degrees", "type": "integer"},
                    {"name": "RelativeHumidity", "type": "integer", "description": "0-100%"},
                    {"name": "UVIndex", "type": "integer", "description": "0-16"},
                ],
            },
            {
                "path": "/forecasts/daily/5day/{locationKey}",
                "method": "GET",
                "description": "5-day daily forecast",
                "params": [
                    {"name": "locationKey", "in": "path", "type": "string", "required": True},
                    {"name": "metric", "in": "query", "type": "boolean", "required": False},
                ],
                "response_fields": [
                    {"name": "DailyForecasts[].Date", "type": "string", "description": "ISO8601 date"},
                    {"name": "DailyForecasts[].Temperature.Maximum.Value", "type": "number"},
                    {"name": "DailyForecasts[].Temperature.Minimum.Value", "type": "number"},
                    {"name": "DailyForecasts[].Day.PrecipitationProbability", "type": "integer"},
                    {"name": "DailyForecasts[].Day.Icon", "type": "integer"},
                    {"name": "DailyForecasts[].AirAndPollen[].Value", "type": "number"},
                ],
            },
        ],
        "sdk_examples": {
            "python": "import requests\nresp = requests.get('https://api.accuweather-enterprise.com/v3/current-conditions/337169', headers={'X-API-Key': API_KEY})\ndata = resp.json()",
        },
    },
    "market_pulse_events": {
        "access_type": "sns_topic",
        "topic_details": {
            "topic_arn": "arn:aws:sns:us-east-1:438291045612:MarketPulseEvents-prod",
            "protocol": "AWS SNS",
            "message_format": "JSON",
            "delivery_frequency": "Real-time (<50ms)",
            "subscription_filter_policy_supported": True,
            "dlq_arn": "arn:aws:sqs:us-east-1:YOUR_ACCOUNT:MarketPulse-DLQ",
            "encryption": "SSE-SQS (AES-256)",
            "how_to_subscribe": "Raise IT ticket 'SNS Subscription Request' with your SQS ARN and desired filter policy. Provisioning SLA: 2 business days.",
        },
        "filter_policy_fields": ["event_type", "asset_class", "exchange", "currency"],
        "message_schema": {
            "event_type": {"type": "string", "enum": ["TRADE", "QUOTE", "NEWS", "CORPORATE_ACTION", "HALT"]},
            "asset_class": {"type": "string", "enum": ["EQUITY", "FX", "COMMODITY", "FIXED_INCOME", "INDEX"]},
            "timestamp_utc": {"type": "string", "format": "ISO8601 microseconds"},
            "instrument_id": {"type": "string", "description": "ISIN (equities) or vendor symbol (FX/Commodity)"},
            "exchange_mic": {"type": "string", "description": "ISO 10383 MIC code e.g. XNAS, XNYS"},
            "price": {"type": "number", "nullable": True, "description": "Null for NEWS/HALT events"},
            "volume": {"type": "integer", "nullable": True},
            "bid": {"type": "number", "nullable": True, "description": "Best bid (QUOTE events)"},
            "ask": {"type": "number", "nullable": True, "description": "Best ask (QUOTE events)"},
            "currency": {"type": "string", "format": "ISO4217"},
            "source_feed": {"type": "string", "enum": ["REFINITIV", "ICE", "DIRECT_EXCHANGE"]},
            "sequence_number": {"type": "integer", "description": "Monotonic per feed — use for gap detection"},
            "metadata": {"type": "object", "description": "Event-type specific payload"},
        },
        "sample_message": {
            "event_type": "TRADE",
            "asset_class": "EQUITY",
            "timestamp_utc": "2026-03-04T14:30:01.234567Z",
            "instrument_id": "US0231351067",
            "exchange_mic": "XNYS",
            "price": 182.45,
            "volume": 1500,
            "bid": None,
            "ask": None,
            "currency": "USD",
            "source_feed": "REFINITIV",
            "sequence_number": 8472910,
            "metadata": {"trade_condition": "regular", "sale_condition_code": "@"},
        },
    },
    "geo_matrix_demographics": {
        "access_type": "datalake",
        "connection": {
            "type": "s3_delta_lake",
            "s3_bucket": "company-third-party-data",
            "s3_prefix": "geo-matrix-demographics/v2/",
            "format": "Delta Lake (Parquet + transaction log)",
            "aws_account": "YOUR_ACCOUNT_ID",
            "iam_role": "arn:aws:iam::YOUR_ACCOUNT_ID:role/GeoMatrixReader",
            "region": "us-east-1",
            "how_to_access": "Assume GeoMatrixReader role via STS. Use Delta-rs, PySpark, or AWS Glue. Tables registered in Glue Catalog as database 'geo_matrix'.",
        },
        "tables": [
            {
                "name": "zip_demographics",
                "s3_path": "s3://company-third-party-data/geo-matrix-demographics/v2/zip_demographics/",
                "description": "Demographic and socioeconomic attributes per US ZIP code",
                "partition_keys": ["vintage_year"],
                "row_count_approx": "33000 per vintage year",
                "columns": [
                    {"name": "zip_code", "type": "STRING", "nullable": False, "pii": False, "description": "5-digit US ZIP code"},
                    {"name": "state_fips", "type": "STRING", "nullable": False, "pii": False},
                    {"name": "county_fips", "type": "STRING", "nullable": False, "pii": False},
                    {"name": "total_population", "type": "LONG", "nullable": True, "pii": False},
                    {"name": "median_household_income", "type": "DOUBLE", "nullable": True, "pii": False},
                    {"name": "median_age", "type": "DOUBLE", "nullable": True, "pii": False},
                    {"name": "pct_college_educated", "type": "DOUBLE", "nullable": True, "pii": False},
                    {"name": "pct_homeowner", "type": "DOUBLE", "nullable": True, "pii": False},
                    {"name": "unemployment_rate", "type": "DOUBLE", "nullable": True, "pii": False},
                    {"name": "pop_density_per_sqmi", "type": "DOUBLE", "nullable": True, "pii": False},
                    {"name": "income_quintile", "type": "INTEGER", "nullable": True, "pii": False, "description": "1=lowest 20%, 5=highest 20%"},
                    {"name": "esri_tapestry_segment", "type": "STRING", "nullable": True, "pii": False, "description": "ESRI lifestyle segment code"},
                    {"name": "vintage_year", "type": "INTEGER", "nullable": False, "pii": False, "description": "Partition key — ACS vintage year"},
                ],
            },
        ],
        "sample_queries": {
            "data_scientist": "from deltalake import DeltaTable\ndt = DeltaTable('s3://company-third-party-data/geo-matrix-demographics/v2/zip_demographics/')\ndf = dt.to_pandas(filters=[('vintage_year', '=', 2025)])",
            "data_engineer": "spark.read.format('delta').load('s3://company-third-party-data/geo-matrix-demographics/v2/zip_demographics/').filter('vintage_year = 2025').groupBy('state_fips').agg(avg('median_household_income')).show()",
        },
    },
    "transact_iq": {
        "access_type": "datalake",
        "connection": {
            "type": "s3_parquet",
            "s3_bucket": "company-third-party-data",
            "s3_prefix": "transact-iq/aggregated/",
            "format": "Parquet (Snappy compressed)",
            "partition_scheme": "region={region}/category={merchant_category}/week_ending={week_ending_date}/",
            "iam_role": "arn:aws:iam::YOUR_ACCOUNT_ID:role/TransactIQReader",
            "glue_database": "transact_iq",
            "note": "Data is aggregated — NO individual transaction records. Minimum cell size 100 to prevent re-identification.",
        },
        "tables": [
            {
                "name": "spend_aggregates_weekly",
                "description": "Weekly aggregated consumer spend by region + merchant category",
                "partition_keys": ["region", "merchant_category", "week_ending_date"],
                "columns": [
                    {"name": "region", "type": "STRING", "nullable": False, "pii": False, "description": "US Census region"},
                    {"name": "merchant_category_code", "type": "STRING", "nullable": False, "pii": False, "description": "ISO 18245 MCC"},
                    {"name": "merchant_category", "type": "STRING", "nullable": False, "pii": False},
                    {"name": "week_ending_date", "type": "DATE", "nullable": False, "pii": False, "description": "Saturday end-of-week"},
                    {"name": "income_quintile", "type": "INTEGER", "nullable": False, "pii": False, "description": "1-5 (suppressed if <100 cardholders)"},
                    {"name": "transaction_count_index", "type": "DOUBLE", "nullable": True, "pii": False, "description": "Indexed to 100 = 2019 baseline"},
                    {"name": "spend_volume_index", "type": "DOUBLE", "nullable": True, "pii": False, "description": "Indexed to 100 = 2019 baseline"},
                    {"name": "avg_ticket_band", "type": "STRING", "nullable": True, "pii": False, "description": "LOW/MEDIUM/HIGH/VERY_HIGH"},
                    {"name": "yoy_growth_pct", "type": "DOUBLE", "nullable": True, "pii": False},
                ],
            },
        ],
    },
    "health_insights_pro": {
        "access_type": "database",
        "connection": {
            "type": "redshift",
            "cluster_endpoint": "iqvia-share.cluster.us-east-1.redshift.amazonaws.com:5439",
            "database": "health_insights",
            "schema": "claims_deidentified",
            "auth_method": "IAM Role + Redshift Data API",
            "iam_role": "arn:aws:iam::YOUR_ACCOUNT_ID:role/HealthInsightsReader",
            "note": "De-identified per HIPAA Safe Harbor. No direct identifiers. Quasi-identifier suppression applied. Access requires HIPAA training certification — attach cert to IT access request.",
        },
        "tables": [
            {
                "name": "medical_claims",
                "description": "De-identified medical claims (inpatient/outpatient/professional)",
                "row_count_approx": "2.1B",
                "columns": [
                    {"name": "claim_id_hash", "type": "VARCHAR(64)", "nullable": False, "pii": False, "description": "Hashed claim ID — stable across updates"},
                    {"name": "patient_token", "type": "VARCHAR(64)", "nullable": False, "pii": False, "description": "Longitudinal patient token — HIPAA Safe Harbor compliant"},
                    {"name": "service_date_year_month", "type": "CHAR(7)", "nullable": False, "pii": False, "description": "YYYY-MM — dates generalised per HIPAA"},
                    {"name": "age_band", "type": "VARCHAR(8)", "nullable": True, "pii": False, "description": "0-17 / 18-34 / 35-44 / 45-54 / 55-64 / 65+"},
                    {"name": "gender_code", "type": "CHAR(1)", "nullable": True, "pii": False},
                    {"name": "primary_icd10_cm", "type": "VARCHAR(8)", "nullable": True, "pii": False, "description": "ICD-10-CM diagnosis code"},
                    {"name": "primary_cpt", "type": "VARCHAR(8)", "nullable": True, "pii": False, "description": "CPT procedure code"},
                    {"name": "drg_code", "type": "VARCHAR(8)", "nullable": True, "pii": False, "description": "MS-DRG (inpatient only)"},
                    {"name": "provider_specialty_code", "type": "VARCHAR(8)", "nullable": True, "pii": False, "description": "CMS specialty code"},
                    {"name": "payer_type", "type": "VARCHAR(32)", "nullable": True, "pii": False, "description": "COMMERCIAL / MEDICARE / MEDICAID / SELF_PAY"},
                    {"name": "allowed_amount_band", "type": "VARCHAR(16)", "nullable": True, "pii": False, "description": "Banded allowed amount"},
                ],
            },
        ],
    },
    "brand_sense_360": {
        "access_type": "saas_api",
        "base_url": "https://api.brandwatch.com/v3",
        "auth_method": "OAuth2 Client Credentials",
        "rate_limits": {"requests_per_minute": 60, "requests_per_day": 50000},
        "endpoints": [
            {
                "path": "/mentions",
                "method": "GET",
                "description": "Retrieve brand mentions with filtering",
                "params": [
                    {"name": "queryId", "in": "query", "type": "integer", "required": True, "description": "Pre-configured Brandwatch query ID"},
                    {"name": "startDate", "in": "query", "type": "string", "required": True, "description": "ISO8601 date"},
                    {"name": "endDate", "in": "query", "type": "string", "required": True},
                    {"name": "pageSize", "in": "query", "type": "integer", "required": False, "description": "Max 5000"},
                    {"name": "sentiment", "in": "query", "type": "string", "enum": ["positive", "neutral", "negative"], "required": False},
                    {"name": "source", "in": "query", "type": "string", "enum": ["twitter", "instagram", "reddit", "news", "blogs"], "required": False},
                ],
                "response_fields": [
                    {"name": "results[].id", "type": "string"},
                    {"name": "results[].date", "type": "string"},
                    {"name": "results[].sentiment", "type": "string"},
                    {"name": "results[].sentimentScore", "type": "number", "description": "-1.0 to 1.0"},
                    {"name": "results[].reach", "type": "integer"},
                    {"name": "results[].source", "type": "string"},
                    {"name": "results[].author.name", "type": "string"},
                    {"name": "results[].location.country", "type": "string"},
                ],
            },
        ],
        "webhook_delivery": {
            "supported": True,
            "events": ["new_mention", "sentiment_spike", "volume_threshold"],
            "payload_format": "JSON over HTTPS POST",
        },
    },
    "supply_shield_risk": {
        "access_type": "saas_api",
        "base_url": "https://api.dnb.com/v1",
        "auth_method": "API Key + JWT (15-min tokens)",
        "rate_limits": {"requests_per_minute": 120, "requests_per_day": 100000},
        "endpoints": [
            {
                "path": "/data/duns/{duns_number}/risk",
                "method": "GET",
                "description": "Comprehensive risk profile for a DUNS number",
                "response_fields": [
                    {"name": "delinquencyScore", "type": "integer", "description": "1-100 (100=lowest risk)"},
                    {"name": "failureScore", "type": "integer", "description": "1-100"},
                    {"name": "paydexScore", "type": "integer", "description": "Payment performance 0-100"},
                    {"name": "sanctionScreening.status", "type": "string", "enum": ["CLEAR", "MATCH", "POSSIBLE_MATCH"]},
                    {"name": "esgScore.environmental", "type": "number"},
                    {"name": "esgScore.social", "type": "number"},
                    {"name": "esgScore.governance", "type": "number"},
                    {"name": "financialStrength.rating", "type": "string"},
                    {"name": "newsRisk.recentAlerts", "type": "array"},
                ],
            },
        ],
        "alert_subscription": {
            "type": "optional_sns",
            "topic_arn": "arn:aws:sns:us-east-1:438291045612:SupplyShieldAlerts-prod",
            "alert_types": ["SANCTION_MATCH", "SCORE_DEGRADATION", "BANKRUPTCY_FILING", "NEWS_RISK"],
        },
    },
}

QUALITY_METRICS = {
    "credit_pulse_pro": {
        "overall_score": 98.5,
        "dimensions": {
            "completeness": 98.7,
            "accuracy": 99.2,
            "timeliness": 99.8,
            "uniqueness": 100.0,
            "consistency": 97.5,
        },
        "last_assessed": "2026-02-28",
        "assessment_frequency": "Weekly automated + Monthly manual",
        "known_issues": [
            {"severity": "low", "description": "0.3% of ZIP codes require USPS standardisation before join", "workaround": "Use CONSUMER_CREDIT.ZIP_XREF lookup table"},
            {"severity": "low", "description": "DEBT_TO_INCOME_BAND null rate ~1.4% for thin-file consumers"},
        ],
        "sla": {"availability": "99.9%", "data_delivery_by": "06:00 ET daily", "incident_response": "4 hours"},
        "historical_trend": "stable",
    },
    "weather_core_api": {
        "overall_score": 99.1,
        "dimensions": {
            "completeness": 99.5,
            "accuracy": 98.8,
            "timeliness": 99.9,
            "uniqueness": 100.0,
            "consistency": 99.0,
        },
        "last_assessed": "2026-03-01",
        "assessment_frequency": "Continuous (automated)",
        "known_issues": [
            {"severity": "info", "description": "Forecast accuracy degrades beyond 72h (expected for weather data)"},
        ],
        "sla": {"availability": "99.99%", "incident_response": "1 hour"},
        "historical_trend": "stable",
    },
    "brand_sense_360": {
        "overall_score": 87.0,
        "dimensions": {
            "completeness": 85.0,
            "accuracy": 88.0,
            "timeliness": 95.0,
            "uniqueness": 99.0,
            "consistency": 82.0,
        },
        "last_assessed": "2026-02-20",
        "assessment_frequency": "Monthly",
        "known_issues": [
            {"severity": "medium", "description": "Instagram data incomplete due to API v2 restrictions — reach data unavailable for private accounts (~18% of mentions)", "workaround": "Use public_reach_only flag in analysis"},
            {"severity": "low", "description": "Sentiment model accuracy lower for non-English content (~79% vs ~91% English)"},
        ],
        "sla": {"availability": "99.5%", "incident_response": "8 hours"},
        "historical_trend": "degrading_slightly",
    },
    "geo_matrix_demographics": {
        "overall_score": 95.2,
        "dimensions": {
            "completeness": 97.0,
            "accuracy": 95.5,
            "timeliness": 88.0,
            "uniqueness": 100.0,
            "consistency": 96.0,
        },
        "last_assessed": "2026-01-15",
        "assessment_frequency": "Per-vintage on delivery",
        "known_issues": [
            {"severity": "low", "description": "~120 rural ZIP codes suppressed for statistical reliability (<500 population)"},
            {"severity": "info", "description": "2025 vintage based on 2019-2023 ACS 5-year estimates — areas with rapid demographic change may lag"},
        ],
        "sla": {"delivery": "Within 30 days of ACS release"},
        "historical_trend": "stable",
    },
    "market_pulse_events": {
        "overall_score": 99.6,
        "dimensions": {
            "completeness": 99.7,
            "accuracy": 99.8,
            "timeliness": 99.9,
            "uniqueness": 100.0,
            "consistency": 99.0,
        },
        "last_assessed": "2026-03-04",
        "assessment_frequency": "Continuous (sequence gap monitoring)",
        "known_issues": [
            {"severity": "info", "description": "During market open/close, brief latency spikes to 200ms (vs typical <50ms)"},
        ],
        "sla": {"availability": "99.95%", "latency_p99": "200ms", "incident_response": "15 minutes"},
        "historical_trend": "stable",
    },
    "transact_iq": {
        "overall_score": 94.0,
        "dimensions": {
            "completeness": 96.0,
            "accuracy": 95.0,
            "timeliness": 85.0,
            "uniqueness": 100.0,
            "consistency": 93.0,
        },
        "last_assessed": "2026-02-15",
        "assessment_frequency": "Weekly on delivery",
        "known_issues": [
            {"severity": "medium", "description": "T+7 lag means latest week unavailable until following Saturday"},
            {"severity": "low", "description": "Cells with <100 cardholders suppressed — affects rural geographies disproportionately"},
            {"severity": "low", "description": "Holiday weeks show anomalous spend patterns — flag in models"},
        ],
        "sla": {"delivery": "Every Saturday by 10:00 ET"},
        "historical_trend": "stable",
    },
    "health_insights_pro": {
        "overall_score": 96.0,
        "dimensions": {
            "completeness": 97.0,
            "accuracy": 97.5,
            "timeliness": 78.0,
            "uniqueness": 99.5,
            "consistency": 95.5,
        },
        "last_assessed": "2026-02-01",
        "assessment_frequency": "Monthly on delivery",
        "known_issues": [
            {"severity": "medium", "description": "Claims lag: 30-45 days post-service date. Avoid month-end analysis for recent periods"},
            {"severity": "info", "description": "ICD-10 coding accuracy varies by provider type — academic centres score highest"},
            {"severity": "low", "description": "Self-pay claims (~8%) have limited procedure code detail"},
        ],
        "sla": {"delivery": "Monthly, within 45 days of month-end"},
        "historical_trend": "stable",
    },
    "supply_shield_risk": {
        "overall_score": 93.5,
        "dimensions": {
            "completeness": 90.0,
            "accuracy": 96.0,
            "timeliness": 98.0,
            "uniqueness": 100.0,
            "consistency": 94.0,
        },
        "last_assessed": "2026-02-28",
        "assessment_frequency": "Monthly",
        "known_issues": [
            {"severity": "medium", "description": "ESG scores only available for ~60% of entities (those with public reporting)"},
            {"severity": "low", "description": "Private company financials coverage lower than public companies (~70% vs ~98%)"},
        ],
        "sla": {"availability": "99.9%", "score_refresh": "Daily", "incident_response": "4 hours"},
        "historical_trend": "improving",
    },
}

# Procurement metadata is mocked as if pre-extracted from PDF contracts.
# In production: use pdfplumber + Claude to extract on ingest, cache here.
LEGAL_METADATA = {
    "credit_pulse_pro": {
        "contract_pdf": "Experian_DataServices_MSA_2024_v2.pdf",
        "compliance_frameworks": ["FCRA", "GLBA", "CCPA", "CPRA"],
        "pii_present": True,
        "pii_fields": ["CONSUMER_HASH_ID (hashed — still considered PII under FCRA)"],
        "ml_training_allowed": False,
        "model_development_allowed": "Allowed only for credit risk, fraud, identity — must not train general-purpose models",
        "redistribution_allowed": False,
        "sublicensing_allowed": False,
        "geographic_restrictions": "US residents only",
        "purpose_limitations": ["credit risk assessment", "fraud detection", "identity verification", "account management"],
        "prohibited_uses": ["employment screening", "housing decisions without FCRA notice", "general ML pre-training", "resale or redistribution"],
        "data_retention_policy": "90-day maximum retention of extracted records; bulk data must be deleted on contract termination",
        "data_processing_agreement_required": True,
        "dpa_signed_date": "2022-03-10",
        "breach_notification_obligation": "Notify Experian within 72 hours of discovery",
        "audit_rights": "Vendor may audit annually with 30 days notice",
        "key_restrictions_summary": "FCRA permissible purpose required per query. No ML pre-training. 90-day data retention. Employment/housing use prohibited.",
    },
    "weather_core_api": {
        "contract_pdf": "AccuWeather_Enterprise_Agreement_2023.pdf",
        "compliance_frameworks": ["Standard commercial SaaS terms"],
        "pii_present": False,
        "ml_training_allowed": True,
        "model_development_allowed": "Unrestricted for internal models",
        "redistribution_allowed": False,
        "sublicensing_allowed": False,
        "geographic_restrictions": None,
        "purpose_limitations": ["internal business use"],
        "prohibited_uses": ["resale of raw API responses", "building a competing weather service"],
        "data_retention_policy": "No explicit retention limit for derived/aggregated data",
        "data_processing_agreement_required": False,
        "key_restrictions_summary": "Low restriction. ML training allowed. No redistribution of raw data. No PII concerns.",
    },
    "brand_sense_360": {
        "contract_pdf": "Brandwatch_Enterprise_License_2023.pdf",
        "compliance_frameworks": ["Twitter/X Developer Policy", "Instagram Graph API Policy", "Reddit API Terms", "GDPR (EU content)"],
        "pii_present": True,
        "pii_fields": ["author.name (public usernames — pseudonymous PII under GDPR)"],
        "ml_training_allowed": "Allowed for internal sentiment/NLP models only",
        "redistribution_allowed": False,
        "sublicensing_allowed": False,
        "geographic_restrictions": "EU mention data subject to GDPR — store in EU or with SCCs",
        "purpose_limitations": ["brand monitoring", "market research", "internal analytics"],
        "prohibited_uses": ["surveillance of individuals", "re-identification of authors", "redistribution of raw mention data"],
        "data_retention_policy": "Raw mention data: 2-year maximum. Aggregated: unrestricted.",
        "data_processing_agreement_required": True,
        "key_restrictions_summary": "Platform TOS apply on top of Brandwatch license. GDPR applies to EU mentions. No individual surveillance. 2-year raw data retention.",
    },
    "geo_matrix_demographics": {
        "contract_pdf": "ESRI_DataPlus_License_2024.pdf",
        "compliance_frameworks": ["Census Bureau data use terms", "ESRI end-user license"],
        "pii_present": False,
        "ml_training_allowed": True,
        "redistribution_allowed": False,
        "sublicensing_allowed": False,
        "geographic_restrictions": None,
        "purpose_limitations": ["internal analytics and modelling"],
        "prohibited_uses": ["redistribution", "creating derivative products for sale"],
        "data_retention_policy": "Retain current and prior vintage only",
        "data_processing_agreement_required": False,
        "key_restrictions_summary": "Low restriction. No PII. ML training allowed. No redistribution. Keep current + prior vintage only.",
    },
    "market_pulse_events": {
        "contract_pdf": "Refinitiv_LSEG_DataLicense_2023.pdf",
        "compliance_frameworks": ["LSEG Market Data Distribution Policy", "MiFID II (EU)", "Reg NMS (US)"],
        "pii_present": False,
        "ml_training_allowed": "Allowed for internal quantitative models",
        "redistribution_allowed": False,
        "sublicensing_allowed": False,
        "geographic_restrictions": None,
        "purpose_limitations": ["internal trading, risk, and research use"],
        "prohibited_uses": ["redistribution to third parties", "display to non-licensed users", "building real-time market data terminals for resale"],
        "data_retention_policy": "Real-time: consume and discard. Historical: permitted, must not be redistributed.",
        "per_user_licensing": True,
        "licensed_user_count": 15,
        "data_processing_agreement_required": False,
        "key_restrictions_summary": "Per-user licensing enforced (15 seats). No redistribution. MiFID II obligations may apply for EU operations. ML for internal quant use is allowed.",
    },
    "transact_iq": {
        "contract_pdf": "Mastercard_DataServices_Agreement_2022.pdf",
        "compliance_frameworks": ["CCPA", "CPRA", "PCI-DSS (vendor-side)", "GLBA"],
        "pii_present": False,
        "pii_fields": ["None — aggregated/anonymised only; minimum cell size 100 applied by vendor"],
        "ml_training_allowed": True,
        "redistribution_allowed": False,
        "sublicensing_allowed": False,
        "geographic_restrictions": None,
        "purpose_limitations": ["consumer analytics", "market sizing", "economic research", "internal decision-making"],
        "prohibited_uses": ["attempting to re-identify individuals", "combining with other datasets to re-identify", "redistribution"],
        "data_retention_policy": "3-year rolling window; older vintages must be deleted",
        "data_processing_agreement_required": True,
        "key_restrictions_summary": "No PII (aggregated only). ML training allowed. No re-identification attempts. 3-year rolling retention. Strong anti-aggregation restrictions.",
    },
    "health_insights_pro": {
        "contract_pdf": "IQVIA_DataLicense_HIPAA_BAA_2023.pdf",
        "compliance_frameworks": ["HIPAA", "HITECH", "21st Century Cures Act"],
        "pii_present": False,
        "pii_fields": ["None — de-identified per HIPAA Safe Harbor. patient_token is a longitudinal token, not PHI."],
        "ml_training_allowed": "Allowed for healthcare analytics models; prohibited for insurance underwriting",
        "redistribution_allowed": False,
        "sublicensing_allowed": False,
        "geographic_restrictions": None,
        "purpose_limitations": ["health economics research", "clinical analytics", "population health", "drug commercialisation"],
        "prohibited_uses": ["insurance underwriting decisions", "re-identification attempts", "redistribution", "any use that would create PHI"],
        "data_retention_policy": "5-year maximum; annual deletion of data beyond rolling window required",
        "baa_signed": True,
        "baa_date": "2023-02-28",
        "hipaa_training_required": True,
        "data_processing_agreement_required": True,
        "key_restrictions_summary": "HIPAA BAA in place. HIPAA training mandatory before access. No insurance underwriting. No re-identification. 5-year retention limit. Most restricted dataset in portfolio.",
    },
    "supply_shield_risk": {
        "contract_pdf": "DnB_API_Services_Agreement_2024.pdf",
        "compliance_frameworks": ["Standard commercial API terms", "GDPR (EU entity data)", "OFAC/Sanctions compliance obligations"],
        "pii_present": True,
        "pii_fields": ["Company officer names in newsRisk.recentAlerts — treat as personal data under GDPR"],
        "ml_training_allowed": "Allowed for internal risk models",
        "redistribution_allowed": False,
        "sublicensing_allowed": False,
        "geographic_restrictions": "EU company data subject to GDPR",
        "purpose_limitations": ["supplier due diligence", "risk monitoring", "procurement decisions"],
        "prohibited_uses": ["redistribution", "consumer credit decisions (not a consumer bureau)", "automated adverse action without human review for material decisions"],
        "data_retention_policy": "No explicit limit for risk scores; raw API response cache must not exceed 30 days",
        "data_processing_agreement_required": True,
        "key_restrictions_summary": "Moderate restrictions. Some GDPR obligations for EU entities. Sanctions screening data requires careful handling. No redistribution. 30-day response cache limit.",
    },
}

PROCUREMENT = {
    "credit_pulse_pro": {
        "contract_pdf": "Experian_DataServices_MSA_2024_v2.pdf",
        "vendor_full_name": "Experian Information Solutions, Inc.",
        "contract_type": "Master Services Agreement + Data Schedule",
        "contract_status": "Active",
        "effective_date": "2024-01-15",
        "term": "3 years",
        "renewal_date": "2027-01-14",
        "auto_renewal": True,
        "termination_notice_days": 90,
        "annual_value_usd": 50000,
        "total_contract_value_usd": 150000,
        "payment_terms": "Annual, net 30, invoiced January",
        "pricing_model": "Flat annual license (unlimited queries within rate limit)",
        "api_call_limit": "10M queries/month included; $0.005/query overage",
        "current_monthly_usage_pct": 23.4,
        "contract_owner_internal": "Jane Smith, Procurement (jane.smith@company.internal)",
        "executive_sponsor": "CRO",
        "vendor_csm": "vendor-csm@experian.com",
        "alternatives_evaluated": ["TransUnion OneConnect", "Equifax DataX", "LexisNexis Risk Solutions"],
        "notes": "5% discount available for early renewal (before Oct 2026). Volume discount tier at 15M queries/month.",
    },
    "weather_core_api": {
        "contract_pdf": "AccuWeather_Enterprise_Agreement_2023.pdf",
        "vendor_full_name": "AccuWeather, Inc.",
        "contract_type": "Enterprise API License",
        "contract_status": "Active",
        "effective_date": "2023-07-01",
        "term": "2 years",
        "renewal_date": "2025-06-30",
        "auto_renewal": True,
        "termination_notice_days": 60,
        "annual_value_usd": 5000,
        "payment_terms": "Annual, net 30",
        "pricing_model": "Tiered by API call volume",
        "api_call_limit": "10M calls/month",
        "current_monthly_usage_pct": 67.0,
        "contract_owner_internal": "Data Platform Team (data-platform@company.internal)",
        "alternatives_evaluated": ["OpenWeatherMap Enterprise", "Tomorrow.io", "IBM Weather Company"],
        "notes": "Contract up for renewal June 2025 — initiate renegotiation by April 2025. Consider upgrading to 25M call tier given 67% utilisation.",
    },
    "brand_sense_360": {
        "contract_pdf": "Brandwatch_Enterprise_License_2023.pdf",
        "vendor_full_name": "Brandwatch Ltd (Cision Group)",
        "contract_type": "SaaS Enterprise License",
        "contract_status": "Active",
        "effective_date": "2023-01-15",
        "term": "2 years",
        "renewal_date": "2025-01-14",
        "auto_renewal": False,
        "termination_notice_days": 30,
        "annual_value_usd": 30000,
        "payment_terms": "Annual upfront",
        "pricing_model": "Per-seat + mention volume tier",
        "seats_included": 10,
        "current_monthly_usage_pct": 58.0,
        "contract_owner_internal": "Marketing Analytics Team",
        "alternatives_evaluated": ["Sprinklr", "Meltwater", "Talkwalker"],
        "notes": "Auto-renewal OFF — requires active renewal decision. Brand & Marketing team evaluating Sprinklr as combined social + analytics platform.",
    },
    "geo_matrix_demographics": {
        "contract_pdf": "ESRI_DataPlus_License_2024.pdf",
        "vendor_full_name": "ESRI (Environmental Systems Research Institute)",
        "contract_type": "Data License Agreement",
        "contract_status": "Active",
        "effective_date": "2024-01-01",
        "term": "1 year (renewable)",
        "renewal_date": "2024-12-31",
        "auto_renewal": True,
        "termination_notice_days": 30,
        "annual_value_usd": 20000,
        "payment_terms": "Annual, net 30",
        "pricing_model": "Flat annual license",
        "contract_owner_internal": "Customer Analytics Team",
        "alternatives_evaluated": ["Precisely (Spectrum)", "Claritas", "Experian ConsumerView"],
        "notes": "Good value — used by 15 teams. Evaluate whether Snowflake Marketplace alternative (Precisley ZIP Demographics) at $8K/yr covers requirements.",
    },
    "market_pulse_events": {
        "contract_pdf": "Refinitiv_LSEG_DataLicense_2023.pdf",
        "vendor_full_name": "London Stock Exchange Group (LSEG) Data & Analytics",
        "contract_type": "Market Data License + Redistribution Agreement",
        "contract_status": "Active",
        "effective_date": "2023-06-01",
        "term": "3 years",
        "renewal_date": "2026-05-31",
        "auto_renewal": True,
        "termination_notice_days": 180,
        "annual_value_usd": 95000,
        "payment_terms": "Quarterly, net 30",
        "pricing_model": "Per-user + exchange fees passthrough",
        "licensed_users": 15,
        "per_user_fee_usd": 3500,
        "exchange_fees_annual_usd": 42500,
        "contract_owner_internal": "Quant Research (quant-research@company.internal)",
        "executive_sponsor": "CIO",
        "alternatives_evaluated": ["Bloomberg B-PIPE", "ICE Data Services"],
        "notes": "High value, high cost. 180-day termination notice is long — plan renewals carefully. Adding users requires LSEG notification 30 days in advance.",
    },
    "transact_iq": {
        "contract_pdf": "Mastercard_DataServices_Agreement_2022.pdf",
        "vendor_full_name": "Mastercard Data & Services",
        "contract_type": "Data License Agreement",
        "contract_status": "Active",
        "effective_date": "2022-09-01",
        "term": "3 years",
        "renewal_date": "2025-08-31",
        "auto_renewal": False,
        "termination_notice_days": 60,
        "annual_value_usd": 100000,
        "payment_terms": "Annual, net 60",
        "pricing_model": "Flat license + volume tier",
        "contract_owner_internal": "Consumer Insights Team + Legal",
        "executive_sponsor": "CDO",
        "alternatives_evaluated": ["Visa Consulting & Analytics (VCA)", "Affinity Solutions", "Yodlee"],
        "notes": "Auto-renewal OFF. High-value strategic asset. Renewal negotiation should begin March 2025. Visa VCA offers comparable coverage — benchmark pricing.",
    },
    "health_insights_pro": {
        "contract_pdf": "IQVIA_DataLicense_HIPAA_BAA_2023.pdf",
        "vendor_full_name": "IQVIA Holdings, Inc.",
        "contract_type": "Data License Agreement + HIPAA Business Associate Agreement",
        "contract_status": "Active",
        "effective_date": "2023-03-01",
        "term": "3 years",
        "renewal_date": "2026-02-28",
        "auto_renewal": True,
        "termination_notice_days": 90,
        "annual_value_usd": 200000,
        "payment_terms": "Annual, net 30",
        "pricing_model": "Flat license (specialty-specific modules)",
        "modules_licensed": ["Medical Claims", "Rx Claims", "Provider Master"],
        "contract_owner_internal": "Health Economics + Legal (health-data@company.internal)",
        "executive_sponsor": "Chief Medical Officer",
        "alternatives_evaluated": ["Optum (UHG)", "IBM MarketScan", "Symphony Health (Syneos)"],
        "notes": "Most expensive dataset. HIPAA BAA mandatory. All users must complete HIPAA training before access is granted — IT enforces via training completion check.",
    },
    "supply_shield_risk": {
        "contract_pdf": "DnB_API_Services_Agreement_2024.pdf",
        "vendor_full_name": "Dun & Bradstreet, Inc.",
        "contract_type": "API Services Agreement",
        "contract_status": "Active",
        "effective_date": "2024-01-15",
        "term": "2 years",
        "renewal_date": "2026-01-14",
        "auto_renewal": True,
        "termination_notice_days": 60,
        "annual_value_usd": 35000,
        "payment_terms": "Annual, net 30",
        "pricing_model": "Per-query (volume bands)",
        "api_call_limit": "500K queries/month",
        "current_monthly_usage_pct": 12.0,
        "contract_owner_internal": "Procurement & Risk Team",
        "alternatives_evaluated": ["Coupa Risk Assess", "EcoVadis", "Riskmethods"],
        "notes": "Low utilisation (12%) — consider downgrading to lower query tier at renewal. ESG module is add-on — currently not licensed.",
    },
}

USAGE_STATS = {
    "credit_pulse_pro": {
        "total_teams": 12,
        "total_users": 45,
        "monthly_api_calls_avg": 2340000,
        "monthly_api_calls_limit": 10000000,
        "utilisation_pct": 23.4,
        "top_use_cases": ["fraud detection model features", "credit risk scoring", "customer onboarding decisioning"],
        "top_teams": [
            {"name": "Risk Analytics", "users": 15, "monthly_calls": 1200000, "use_case": "Credit model feature engineering"},
            {"name": "Fraud Prevention", "users": 10, "monthly_calls": 700000, "use_case": "Real-time fraud scoring"},
            {"name": "Customer Onboarding", "users": 8, "monthly_calls": 300000, "use_case": "Identity + credit verification"},
            {"name": "Product Team", "users": 7, "monthly_calls": 140000, "use_case": "Product eligibility rules"},
        ],
        "growth_trend": "increasing",
        "mom_growth_pct": 8.2,
        "peak_usage_window": "09:00-11:00 ET weekdays",
        "data_pipeline_integrations": ["Airflow DAG (daily)", "Snowflake dbt models", "SageMaker feature store"],
    },
    "weather_core_api": {
        "total_teams": 8,
        "total_users": 120,
        "monthly_api_calls_avg": 6700000,
        "monthly_api_calls_limit": 10000000,
        "utilisation_pct": 67.0,
        "top_use_cases": ["logistics route optimisation", "demand forecasting", "risk event alerting"],
        "top_teams": [
            {"name": "Logistics & Ops", "users": 45, "monthly_calls": 3500000, "use_case": "Route risk scoring"},
            {"name": "Demand Planning", "users": 30, "monthly_calls": 2000000, "use_case": "Weather-adjusted demand models"},
            {"name": "Risk Management", "users": 20, "monthly_calls": 800000, "use_case": "Catastrophe event alerting"},
        ],
        "growth_trend": "stable",
        "mom_growth_pct": 1.5,
        "peak_usage_window": "06:00-08:00 ET daily",
        "data_pipeline_integrations": ["Lambda (real-time)", "Airflow DAG (historical backfill)", "Kinesis stream"],
    },
    "brand_sense_360": {
        "total_teams": 5,
        "total_users": 30,
        "monthly_api_calls_avg": 290000,
        "top_use_cases": ["brand health tracking", "campaign measurement", "competitive intelligence"],
        "top_teams": [
            {"name": "Brand & Marketing", "users": 15, "monthly_calls": 180000, "use_case": "Brand health dashboards"},
            {"name": "Product Marketing", "users": 8, "monthly_calls": 70000, "use_case": "Product launch monitoring"},
            {"name": "Competitive Intel", "users": 7, "monthly_calls": 40000, "use_case": "Competitor share of voice"},
        ],
        "growth_trend": "stable",
        "mom_growth_pct": -1.2,
        "data_pipeline_integrations": ["Webhook → Kafka → Databricks", "Scheduled API pull (daily)"],
    },
    "geo_matrix_demographics": {
        "total_teams": 15,
        "total_users": 200,
        "top_use_cases": ["customer segmentation", "market expansion analysis", "store site selection", "pricing strategy"],
        "top_teams": [
            {"name": "Customer Analytics", "users": 60, "monthly_calls": None, "use_case": "Customer demographic enrichment"},
            {"name": "Strategy & Planning", "users": 40, "monthly_calls": None, "use_case": "Market sizing and white-space"},
            {"name": "Retail Site Planning", "users": 30, "monthly_calls": None, "use_case": "Site selection scoring"},
            {"name": "Pricing", "users": 25, "monthly_calls": None, "use_case": "Geographic price elasticity"},
        ],
        "growth_trend": "increasing",
        "mom_growth_pct": 5.0,
        "data_pipeline_integrations": ["Glue ETL → Snowflake", "dbt geo enrichment models", "Tableau/Looker direct query"],
        "note": "Batch access — no API call metrics. Usage measured by Glue job runs and Snowflake query logs.",
    },
    "market_pulse_events": {
        "total_teams": 3,
        "total_users": 15,
        "events_consumed_daily_avg": 12000000,
        "top_use_cases": ["real-time alpha signal generation", "execution analytics", "market microstructure research"],
        "top_teams": [
            {"name": "Quantitative Research", "users": 8, "monthly_calls": None, "use_case": "Alpha signal research"},
            {"name": "Trading Technology", "users": 5, "monthly_calls": None, "use_case": "Execution quality analytics"},
            {"name": "Risk Management", "users": 2, "monthly_calls": None, "use_case": "Real-time market risk"},
        ],
        "growth_trend": "stable",
        "data_pipeline_integrations": ["SNS → SQS → Lambda → TimescaleDB", "SNS → Kinesis → S3 (archive)"],
    },
    "transact_iq": {
        "total_teams": 7,
        "total_users": 35,
        "top_use_cases": ["consumer spend trend analysis", "category benchmarking", "economic nowcasting"],
        "top_teams": [
            {"name": "Consumer Insights", "users": 15, "use_case": "Weekly spend reports"},
            {"name": "Economics Research", "users": 10, "use_case": "Macro spend nowcasting"},
            {"name": "Product Strategy", "users": 6, "use_case": "Category market share"},
        ],
        "growth_trend": "increasing",
        "mom_growth_pct": 12.0,
        "data_pipeline_integrations": ["S3 → Glue → Redshift", "Airflow weekly ingest DAG"],
    },
    "health_insights_pro": {
        "total_teams": 2,
        "total_users": 18,
        "top_use_cases": ["patient journey analytics", "treatment pathway analysis", "market access research"],
        "top_teams": [
            {"name": "Health Economics", "users": 12, "use_case": "Outcomes and RWE research"},
            {"name": "Market Access", "users": 6, "use_case": "Payer mix and reimbursement analysis"},
        ],
        "growth_trend": "stable",
        "access_requirement": "HIPAA training completion mandatory",
        "data_pipeline_integrations": ["Redshift → dbt → internal analytics store"],
    },
    "supply_shield_risk": {
        "total_teams": 3,
        "total_users": 20,
        "monthly_api_calls_avg": 60000,
        "monthly_api_calls_limit": 500000,
        "utilisation_pct": 12.0,
        "top_use_cases": ["supplier onboarding screening", "ongoing supplier monitoring", "sanctions compliance"],
        "top_teams": [
            {"name": "Procurement & Risk", "users": 12, "use_case": "Supplier due diligence"},
            {"name": "Legal & Compliance", "users": 5, "use_case": "Sanctions screening"},
            {"name": "Finance", "users": 3, "use_case": "Counterparty credit risk"},
        ],
        "growth_trend": "stable",
        "data_pipeline_integrations": ["REST API → internal risk DB", "Alert SNS → Slack notifications"],
    },
}
